### ISSUE TITLE
Block times are 60 seconds instead of 30 seconds

### ISSUE THREAD

**Issue by aronschatz** [AirWireOfficial/wire-core#6]
Expected: Block times are averaging around 30 seconds.

Actual: Block times are averaging around 60 seconds.

**Comment by Remapper** [comment]
30 seconds is the target time not actual time, the chain will adjust the difficulty to get as close to the target as it can, it also depends on available inputs and wallets coming on and off the network.
Chainparams.cpp - nTargetSpacing = 1 * 30; // Wire: 30 Seconds
