### ISSUE TITLE
Seed nodes need updating

### ISSUE THREAD

**Issue by aronschatz** [AirWireOfficial/wire-core#7]
The seed nodes built into the wallet are out of date.

1. Airwire needs to create new DNS entries that point to managed wallets for seed nodes.
2. The wallet code needs to be updated to point to the DNS based seed nodes.

**Comment by Remapper** [comment]
An addition seeder will help but I run 6 that are built in to the code and all are up and updated to latest 1.4.0 version (yesterday)
