### ISSUE TITLE
Current updated wallet 1.3.0 is updated on an older version of Wallet

### ISSUE THREAD

**Issue by Nitroplatypus** [AirWireOfficial/wire-core#8]
The current updated version of the wallet 1.4.0 is updated over an older version of the 1.3 wallet not the most recent version v1.3.0.0-32&64bit-V130

The 1.4.0 has different / older UI changes.

**Comment by Remapper** [comment]
1.4.0 Update was done from this code, which images are wrong?

**Comment by Remapper** [comment]
v1.3.0.0-32&64bit-V130 is just the QT marker for GUI wallets

**Comment by Nitroplatypus** [comment]
![image](https://user-images.githubusercontent.com/47160963/52168235-8f1ca780-271f-11e9-9e52-dd0f9ba14c72.png)
![image](https://user-images.githubusercontent.com/47160963/52168242-9fcd1d80-271f-11e9-8072-3cc8f666d309.png)
![image](https://user-images.githubusercontent.com/47160963/52168244-aa87b280-271f-11e9-8cb8-35890f0550e6.png)
All from 1.3.0

**Comment by Nitroplatypus** [comment]
![image](https://user-images.githubusercontent.com/47160963/52168250-bffcdc80-271f-11e9-96db-123fd6ef0851.png)
![image](https://user-images.githubusercontent.com/47160963/52168256-cb500800-271f-11e9-9e05-cfd4ad5bca7b.png)
![image](https://user-images.githubusercontent.com/47160963/52168257-d4d97000-271f-11e9-8bd5-59d79c15296e.png)
From 1.4.0

**Comment by Remapper** [comment]
Icons updated, releases page updated with new windows binary, mac will update after compiled.
